### ISSUE TITLE
Need help installing yadt-shell in CentOS 7

### ISSUE THREAD

**Issue by maarre** [yadt/yadtshell#22]
I am trying to install yadt on a CentOS machine. I need some help because I have got stuck. 
```
[root@yadt yadtshell-1.9.1]# uname -a
Linux yadt 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
The contents of the yadtshell-config package (was hoping there is a --force flag):
```
[root@yadt ~]# mkdir /etc/yadtshell
[root@yadt ~]# echo "LOG_DIR_PREFIX='/var/log/yadtshell'" > /etc/yadtshell/loggingconf.py
```
Preparation installation sequence:
```
[root@yadt ~]# yum install wget.x86_64
[root@yadt ~]# cd /usr/local/src
[root@yadt src]# yum install git.x86_64
[root@yadt src]# git clone https://github.com/yadt/yadtshell
[root@yadt src]# cd yadtshell
[root@yadt yadtshell]# yum install epel-release
[root@yadt yadtshell]# yum install python-pip.noarch
[root@yadt yadtshell]# pip install pybuilder
[root@yadt yadtshell]# yum groupinstall "Development Tools"
[root@yadt yadtshell]# yum install python-devel.x86_64
[root@yadt yadtshell]# pyb install_dependencies
[root@yadt yadtshell]# pyb
[root@yadt yadtshell]# cd target/dist/yadtshell-1.9.1
[root@yadt yadtshell-1.9.1]# ./setup.py bdist_rpm
[root@yadt yadtshell-1.9.1]# yum install python-docopt.noarch
[root@yadt yadtshell-1.9.1]# yum install python-simplejson.x86_64
```
Dependencies:
```
[root@yadt yadtshell-1.9.1]# yum list python-twisted-core.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.vianett.no
 * epel: epel.besthosting.ua
 * extras: centos.uib.no
 * updates: centos.uib.no
Installed Packages
python-twisted-core.x86_64                            12.2.0-4.el7                            @base

[root@yadt yadtshell-1.9.1]# which hostexpand
/bin/hostexpand

[root@yadt yadtshell-1.9.1]# rpm -qf /bin/hostexpand
file /bin/hostexpand is not owned by any package

[root@yadt yadtshell-1.9.1]# hostexpand --version
hostexpand 1.0.2
 ```
 

Installation:
```
[root@yadt yadtshell-1.9.1]# yum install dist/yadtshell-1.9.1-0.noarch.rpm
Loaded plugins: fastestmirror
Examining dist/yadtshell-1.9.1-0.noarch.rpm: yadtshell-1.9.1-0.noarch
Marking dist/yadtshell-1.9.1-0.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package yadtshell.noarch 0:1.9.1-0 will be installed
--> Processing Dependency: python-twisted >= 12 for package: yadtshell-1.9.1-0.noarch
Loading mirror speeds from cached hostfile
 * base: centos.vianett.no
 * epel: epel.besthosting.ua
 * extras: centos.uib.no
 * updates: centos.uib.no
--> Processing Dependency: hostexpand for package: yadtshell-1.9.1-0.noarch
--> Processing Dependency: yadtshell-config for package: yadtshell-1.9.1-0.noarch
--> Finished Dependency Resolution
Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: python-twisted >= 12
Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: hostexpand
Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: yadtshell-config
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
What can I do to solve this?

Thanks

Mårten

**Comment by locolupo** [comment]
Hi Mårten,

> --> Processing Dependency: hostexpand for package: yadtshell-1.9.1-0.noarch
> --> Processing Dependency: yadtshell-config for package: yadtshell-1.9.1-0.noarch
> --> Finished Dependency Resolution
> Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: python-twisted >= 12
Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: hostexpand
Error: Package: yadtshell-1.9.1-0.noarch (/yadtshell-1.9.1-0.noarch)
           Requires: yadtshell-config
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

it looks like that yum can't find the missing hostexpand dependency. The hostexpand project is part of the yadt project (https://github.com/yadt/hostexpand), you can just build hostexpand by your own or you can use our RHEL7/Centos7 Yum repository thats providing all the packages you will need to install yadtshell. (https://github.com/yadt/try-it-yourself).

Marcel

**Comment by maarre** [comment]
Thanks Marcel. I will build hostexand as well. But the dependency to twisted needs to be adressed by you.

Mårten

**Comment by maarre** [comment]
hostexpand was already installed:
```
[root@yadt src]# pip show hostexpand
---
Name: hostexpand
Version: 1.0.2
Location: /usr/lib/python2.7/site-packages
Requires: dnspython
```

**Comment by locolupo** [comment]
Hi Mårten,

yes you installed it via ```pip```, but if you install a rpm Package ```yum``` tries so resolve the dependency of your package. 

> [root@yadt yadtshell-1.9.1]# rpm -qf /bin/hostexpand
> file /bin/hostexpand is not owned by any package

If you like to install Software as rpm, you must provide all dependencies as rpm packages.

Marcel

**Comment by mriehl** [comment]
Also note that python-twisted-core is not enough, you need the full python-twisted RPM.

On a side note, if you're on a throwaway system, you can build "dummy" empty RPMs with FPM to satisfy the dependencies. Or you can just install everything with pip.

**Comment by mriehl** [comment]
We have a python-twisted rpm in the bintray repo, don't we? @locolupo

**Comment by locolupo** [comment]
> We have a python-twisted rpm in the bintray repo, haven't we? @locolupo

@mriehl yes we have 13.2.0 in our repository

afaik you can find the python-twisted package in the epel repository too.

**Comment by mriehl** [comment]
Can you add the link here? Or even better, the `yum.repos.d` entry to add it

**Comment by mriehl** [comment]
@locolupo yeah it's in the SL repo but:
```
python-twisted.noarch == 8.2.0-3.1.el6
```

We require later than 12.0, so.... :rat:

**Comment by maarre** [comment]
```
[root@yadt src]# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.vianett.no
 * epel: epel.besthosting.ua
 * extras: centos.uib.no
 * updates: centos.uib.no
repo id                                       repo name                                                                   status
!base/7/x86_64                                CentOS-7 - Base                                                             8,652
!epel/x86_64                                  Extra Packages for Enterprise Linux 7 - x86_64                              8,121
!extras/7/x86_64                              CentOS-7 - Extras                                                             128
!updates/7/x86_64                             CentOS-7 - Updates                                                            684
repolist: 17,585
[root@yadt src]# yum list | grep twisted
python-twisted-core.x86_64              12.2.0-4.el7                   @base
python-twisted-core-doc.x86_64          12.2.0-4.el7                   base
python-twisted-web.x86_64               12.1.0-4.el7                   base
python-twisted-words.x86_64             12.2.0-4.el7                   base
```

**Comment by locolupo** [comment]
> @locolupo yeah it's in the SL repo but:

>> python-twisted.noarch == 8.2.0-3.1.el6

Yes on centos6 maybe, but not on centos7

**Comment by locolupo** [comment]
i've checked it on a centos7.1 and only twisted-core is part if the base repo

@maarre please use the twisted package thats in our bintray repo:
https://github.com/yadt/try-it-yourself#install-the-rpms

**Comment by maarre** [comment]
I thought maybe I should try to install through pip. 
```
[root@yadt yum-repo-server]# pip install twisted
Requirement already satisfied (use --upgrade to upgrade): twisted in /usr/lib64/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /usr/lib64/python2.7/site-packages (from twisted)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted)
Cleaning up...
```

I have googled but found nothing. Maybe you should check dependencies using pip instead of yum? After all python stuff is installed using pip.

**Comment by maarre** [comment]
locolupo:
> @maarre please use the twisted package thats in our bintray repo:
> https://github.com/yadt/try-it-yourself#install-the-rpms

I had to remove python-twisted-core because of all the conflicts. Maybe it is just a separate packaging. 

The dependency to hostexpand is not a problem anymore.

Now I only have to take care of yadtshell-config

Thanks for all the help!

Mårten

**Comment by maarre** [comment]
It was available from your repo! Without the dependency to yadtshell-config :+1:

**Comment by mriehl** [comment]
If you're comfortable with using pip, note that you can install the entire stack through pip :
`pip install yadtshell`
